name: blt_ota_tool
description: "Bluetooth OTA upgrade tool for OpenBLT"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true